sudo: 
  false

language: 
  c 

services:
  - docker
  
# install mpich  
  - sudo ./install-petsc.sh
  
  
script:
  # 
  # 2. send benchmark file from master to a compute node
  
  # 3. send benchmark result file from compute node to master
