sudo: 
  false

language: 
  c 

services:
  - docker
  
# install mpich  
  - sudo apt-get install -y wget 
  - wget http://www.mpich.org/static/downloads/3.1.3/mpich-3.1.3.tar.gz
  
  
script:
  # 
  # 2. send benchmark file from master to a compute node
  
  # 3. send benchmark result file from compute node to master
