sudo: 
  required

language: 
  c 

services:
  - docker

before_install:
  # update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine mpich libmpich-dev

  # display hosts file
  - cat /etc/hosts

  # Docker networking
  - docker network create --driver bridge network1
  - docker network inspect network1

  # # provision cluster 
  - docker pull ocramz/mpich-docker
  
  - docker run -d --net=network1 -h node01 --name node01cont ocramz/mpich-docker /usr/sbin/sshd –D
  - docker run -d --net=network1 -h node02 --name node02cont ocramz/mpich-docker /usr/sbin/sshd –D

  # the two new containers should now appear in the Docker `bridge` network:
  - docker network inspect network1


  
script:
  # compile test MPI executable
  - mpicc src/helloworld.c -o helloworld



after_success:

  # # # run
  # - mpirun -np 2 -hostlist node01,node02 helloworld
