sudo: 
  required

language: 
  c 

services:
  - docker

addons:
  apt:
    packages:
    - gfortran
    - gcc


before_install:
  # update Docker
  - sudo apt-get update -y 
  - DEBIAN_FRONTEND=noninteractive yes Yes | sudo apt-get -y --force-yes install docker-engine

  # Travis `env` is available only at the `script` phase, and not here :/
  - export PETSC_VERSION=3.7.2
  - export PETSC_DIR=${PWD}/petsc-${PETSC_VERSION}
  - export PETSC_ARCH=arch-linux2-c-debug

  # show environment vars
  - printenv | grep PETSC

  # display hosts file
  - cat /etc/hosts

  - docker network inspect bridge

  # # provision cluster (NB: pulling tag `petsc-3.7.2` from Docker hub): each MPI node runs in a separate Docker container
  - docker pull ocramz/petsc-docker:petsc-3.7.2
  - docker run -d -h node01 --name node01cont ocramz/petsc-docker:petsc-3.7.2 /usr/sbin/sshd –D
  - docker run -d -h node02 --name node02cont ocramz/petsc-docker:petsc-3.7.2 /usr/sbin/sshd –D

  # the two new containers should now appear in the Docker `bridge` network:
  - docker network inspect bridge


  
script:
  # install PETSc
  - sudo ./install-petsc.sh ${PETSC_VERSION} ${PETSC_DIR}

  # compile test MPI executable
  - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpicc src/helloworld.c -o helloworld



after_success:


  # # # run
  # - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpirun -np 2 -hostlist node01,node02 helloworld
