sudo: 
  required

language: 
  c 

services:
  - docker

addons:
  apt:
    packages:
    - gfortran
    - gcc

before_install:  
  - sudo ./install-petsc.sh
  
script:
  - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpicc src/helloworld.c -o helloworld

  # provision cluster
  - docker pull ocramz/petsc-docker:petsc-3.7
  - docker run -d -h node01 --name cont01 ocramz/petsc-docker:petsc-3.7 /usr/sbin/sshd –D
  - docker run -d -h node02 --name cont01 ocramz/petsc-docker:petsc-3.7 /usr/sbin/sshd –D
  
  # run
  - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpirun -np 2 -hostlist node01,node02 helloworld
