sudo: 
  required

language: 
  c 

services:
  - docker

addons:
  apt:
    packages:
    - gfortran
    - gcc


before_install:
  # Travis `env` is available only at the `script` phase, and not here :/
  - export PETSC_VERSION=3.7.2
  - export PETSC_DIR=/opt/petsc-${PETSC_VERSION}
  - export PETSC_ARCH=arch-linux2-c-debug
  - sudo ./install-petsc.sh
  
script:
  - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpicc src/helloworld.c -o helloworld

  # # provision cluster
  - docker pull ocramz/petsc-docker:petsc-3.7.2
  - docker run -d -h node01 --name cont01 ocramz/petsc-docker:petsc-3.7.2 /usr/sbin/sshd –D
  - docker run -d -h node02 --name cont01 ocramz/petsc-docker:petsc-3.7.2 /usr/sbin/sshd –D
  
  # # run
  - ${PETSC_DIR}/${PETSC_ARCH}/bin/mpirun -np 2 -hostlist node01,node02 helloworld
